# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# Solution:

limit = 4000000
fibonacci = [1,2]
even_sum = 0
while fibonacci[-1] + fibonacci[-2] < limit:
  fibonacci.append(fibonacci[-1] + fibonacci[-2])
for num in fibonacci:
  if num%2 == 0:
    even_sum += num
print(even_sum)

# Answer: 4613732