# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
#
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
#
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
#
# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised;
# what is the value of D?

def penta_list(n):
    l = [1, 5]
    for i in range(n):
        l.append(l[-1] + 3*(len(l)+1) - 2)
    return l

list = penta_list(4000)

for n in range(len(list) - 1, -1, -1):
    for m in range(n - 1, -1, -1):
        if (list[n] + list[m] <= list[-1]):
            if (list[n] - list[m] in list and list[n] + list[m] in list):
                print('d =', abs(list[m] - list[n]), ', m =', list[m], ', n =', list[n])
