# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#
# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.

tri = [1]
penta = [1]
hexa = [1]

while (True):
    tri.append(tri[-1] + len(tri) + 1)
    penta.append(penta[-1] + 3*len(penta) + 1)
    hexa.append(hexa[-1] + 4*len(hexa) + 1)
    if (tri[-1] in penta and tri[-1] in hexa):
        print(tri[-1])
